<?php
/**
 * Lightweight dependency-free PDF report generator.
 *
 * Uses PDF built-in Helvetica fonts and vector drawing commands only.
 * No remote resources, user supplied SVG, JavaScript, or executable content is embedded.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

class ILSM_PDF_Report {
    private $pages = array();
    private $content = '';
    private $page_width = 595.28;
    private $page_height = 841.89;
    private $margin = 34;
    private $y = 800;
    private $page_no = 0;
    private $footer_label = 'DMA InternLink Mapper';
    private $images = array();
    private $page_images = array();
    private $brand_logo_cache = null;
    private $site_logo_cache = null;
    private $site_name_cache = null;

    public function __construct( $footer_label = '' ) {
        if ( $footer_label ) { $this->footer_label = (string) $footer_label; }
        $this->new_page();
    }

    public function page_width() { return $this->page_width; }
    public function page_height() { return $this->page_height; }
    public function margin() { return $this->margin; }
    public function current_y() { return $this->y; }
    public function page_number() { return $this->page_no; }

    public function new_page() {
        if ( '' !== $this->content ) { $this->pages[] = $this->content; }
        $this->content = '';
        $this->page_no++;
        $this->y = $this->page_height - $this->margin;
        $this->footer();
    }

    private function footer() {
        $this->line( $this->margin, 31, $this->page_width - $this->margin, 31, 226, 232, 240, 0.45 );
        $this->set_color( 71, 85, 105 );
        $site_name = $this->site_name();
        $this->text( $this->margin, 18, $this->shorten( $site_name, 46 ), 7.2, true );
        $this->set_color( 148, 163, 184 );
        $this->text( 210, 18, __( 'Generated by DMA InternLink Mapper', 'dma-internlink-mapper' ), 6.7 );
        $this->text( $this->page_width - 82, 18, 'Page ' . $this->page_no, 7.2 );
    }

    private function esc( $text ) {
        $text = html_entity_decode( wp_strip_all_tags( (string) $text ), ENT_QUOTES | ENT_HTML5, 'UTF-8' );
        $text = preg_replace( '/[^\x20-\x7E]/', '', $text );
        return str_replace( array( '\\', '(', ')', "\r", "\n" ), array( '\\\\', '\\(', '\\)', ' ', ' ' ), $text );
    }

    public function set_color( $r, $g, $b, $stroke = false ) {
        $this->content .= sprintf( "%.3F %.3F %.3F %s\n", $r / 255, $g / 255, $b / 255, $stroke ? 'RG' : 'rg' );
    }

    public function text( $x, $y, $text, $size = 10, $bold = false ) {
        $font = $bold ? 'F2' : 'F1';
        $this->content .= sprintf( "BT /%s %.2F Tf %.2F %.2F Td (%s) Tj ET\n", $font, $size, $x, $y, $this->esc( $text ) );
    }

    public function rect( $x, $y, $w, $h, $r = 255, $g = 255, $b = 255, $stroke = null ) {
        $this->set_color( $r, $g, $b );
        $this->content .= sprintf( "%.2F %.2F %.2F %.2F re f\n", $x, $y, $w, $h );
        if ( is_array( $stroke ) ) {
            $this->set_color( $stroke[0], $stroke[1], $stroke[2], true );
            $this->content .= sprintf( "%.2F %.2F %.2F %.2F re S\n", $x, $y, $w, $h );
        }
    }

    public function rounded_rect( $x, $y, $w, $h, $radius = 8, $fill = array(255,255,255), $stroke = array(226,232,240) ) {
        $r = min( (float) $radius, $w / 2, $h / 2 ); $k = 0.5522847498; $c = $r * $k;
        $path = sprintf( "%.2F %.2F m ", $x + $r, $y );
        $path .= sprintf( "%.2F %.2F l %.2F %.2F %.2F %.2F %.2F %.2F c ", $x + $w - $r, $y, $x + $w - $r + $c, $y, $x + $w, $y + $r - $c, $x + $w, $y + $r );
        $path .= sprintf( "%.2F %.2F l %.2F %.2F %.2F %.2F %.2F %.2F c ", $x + $w, $y + $h - $r, $x + $w, $y + $h - $r + $c, $x + $w - $r + $c, $y + $h, $x + $w - $r, $y + $h );
        $path .= sprintf( "%.2F %.2F l %.2F %.2F %.2F %.2F %.2F %.2F c ", $x + $r, $y + $h, $x + $r - $c, $y + $h, $x, $y + $h - $r + $c, $x, $y + $h - $r );
        $path .= sprintf( "%.2F %.2F l %.2F %.2F %.2F %.2F %.2F %.2F c h ", $x, $y + $r, $x, $y + $r - $c, $x + $r - $c, $y, $x + $r, $y );
        if ( is_array( $fill ) ) { $this->set_color( $fill[0],$fill[1],$fill[2] ); $this->content .= $path . "f\n"; }
        if ( is_array( $stroke ) ) { $this->set_color( $stroke[0],$stroke[1],$stroke[2], true ); $this->content .= "0.65 w " . $path . "S\n"; }
    }

    public function line( $x1, $y1, $x2, $y2, $r = 203, $g = 213, $b = 225, $width = 1 ) {
        $this->set_color( $r, $g, $b, true );
        $this->content .= sprintf( "%.2F w %.2F %.2F m %.2F %.2F l S\n", $width, $x1, $y1, $x2, $y2 );
    }

    public function circle( $cx, $cy, $radius, $r, $g, $b, $width = 8 ) {
        $k = 0.5522847498; $c = $radius * $k;
        $this->set_color( $r, $g, $b, true );
        $this->content .= sprintf( "%.2F w %.2F %.2F m ", $width, $cx + $radius, $cy );
        $this->content .= sprintf( "%.2F %.2F %.2F %.2F %.2F %.2F c ", $cx + $radius, $cy + $c, $cx + $c, $cy + $radius, $cx, $cy + $radius );
        $this->content .= sprintf( "%.2F %.2F %.2F %.2F %.2F %.2F c ", $cx - $c, $cy + $radius, $cx - $radius, $cy + $c, $cx - $radius, $cy );
        $this->content .= sprintf( "%.2F %.2F %.2F %.2F %.2F %.2F c ", $cx - $radius, $cy - $c, $cx - $c, $cy - $radius, $cx, $cy - $radius );
        $this->content .= sprintf( "%.2F %.2F %.2F %.2F %.2F %.2F c S\n", $cx + $c, $cy - $radius, $cx + $radius, $cy - $c, $cx + $radius, $cy );
    }

    /**
     * Embed a JPEG image on the current page.
     *
     * @param string $jpeg Binary JPEG data.
     * @param int    $pixel_width JPEG pixel width.
     * @param int    $pixel_height JPEG pixel height.
     * @param float  $x PDF x coordinate.
     * @param float  $y PDF y coordinate.
     * @param float  $width Rendered width.
     * @param float  $height Rendered height.
     * @return bool
     */
    public function jpeg_image( $jpeg, $pixel_width, $pixel_height, $x, $y, $width, $height ) {
        if ( ! is_string( $jpeg ) || '' === $jpeg || $pixel_width < 1 || $pixel_height < 1 || $width <= 0 || $height <= 0 ) {
            return false;
        }

        $image_index = count( $this->images ) + 1;
        $name = 'Im' . $image_index;
        $this->images[ $image_index ] = array(
            'name'   => $name,
            'data'   => $jpeg,
            'width'  => (int) $pixel_width,
            'height' => (int) $pixel_height,
        );
        if ( ! isset( $this->page_images[ $this->page_no ] ) ) {
            $this->page_images[ $this->page_no ] = array();
        }
        $this->page_images[ $this->page_no ][] = $image_index;
        $this->content .= sprintf( "q %.2F 0 0 %.2F %.2F %.2F cm /%s Do Q\n", $width, $height, $x, $y, $name );
        return true;
    }

    public function filled_circle( $cx, $cy, $radius, $r, $g, $b ) {
        $k = 0.5522847498; $c = $radius * $k;
        $this->set_color( $r, $g, $b );
        $this->content .= sprintf( "%.2F %.2F m ", $cx + $radius, $cy );
        $this->content .= sprintf( "%.2F %.2F %.2F %.2F %.2F %.2F c ", $cx + $radius, $cy + $c, $cx + $c, $cy + $radius, $cx, $cy + $radius );
        $this->content .= sprintf( "%.2F %.2F %.2F %.2F %.2F %.2F c ", $cx - $c, $cy + $radius, $cx - $radius, $cy + $c, $cx - $radius, $cy );
        $this->content .= sprintf( "%.2F %.2F %.2F %.2F %.2F %.2F c ", $cx - $radius, $cy - $c, $cx - $c, $cy - $radius, $cx, $cy - $radius );
        $this->content .= sprintf( "%.2F %.2F %.2F %.2F %.2F %.2F c f\n", $cx + $c, $cy - $radius, $cx + $radius, $cy - $c, $cx + $radius, $cy );
    }

    public function progress_ring( $cx, $cy, $radius, $percent, $size = 15 ) {
        $percent = max( 0, min( 100, (int) $percent ) );
        $this->circle( $cx, $cy, $radius, 226, 232, 240, 6 );
        $color = $percent >= 90 ? array(22,163,74) : ( $percent >= 70 ? array(217,119,6) : ( $percent >= 50 ? array(234,88,12) : array(220,38,38) ) );
        $segments = max( 1, (int) round( 64 * $percent / 100 ) );
        $this->set_color( $color[0], $color[1], $color[2], true );
        $this->content .= "6 w 1 J\n";
        for ( $i=0; $i<$segments; $i++ ) {
            $a1 = deg2rad( 90 - ( $i * 360 / 64 ) );
            $a2 = deg2rad( 90 - ( ( $i + 0.82 ) * 360 / 64 ) );
            $x1=$cx+$radius*cos($a1); $y1=$cy+$radius*sin($a1); $x2=$cx+$radius*cos($a2); $y2=$cy+$radius*sin($a2);
            $this->content .= sprintf( "%.2F %.2F m %.2F %.2F l S\n", $x1,$y1,$x2,$y2 );
        }
        $this->set_color( 15,23,42 );
        $label=(string)$percent; $offset = strlen($label)>=3 ? 11 : 7;
        $this->text( $cx-$offset, $cy-5, $label, $size, true );
        $this->set_color( 100,116,139 ); $this->text( $cx-9, $cy-17, '/100', 6.5 );
    }

    public function wrapped_text( $x, $y, $text, $max_chars = 75, $size = 9, $line_height = 13, $bold = false, $max_lines = 0 ) {
        $words = preg_split( '/\s+/', trim( $this->esc( $text ) ) ); $lines=array(); $line='';
        foreach ( $words as $word ) { $candidate = '' === $line ? $word : $line . ' ' . $word; if ( strlen($candidate)>$max_chars && ''!==$line ) { $lines[]=$line; $line=$word; } else { $line=$candidate; } }
        if ( ''!==$line ) { $lines[]=$line; }
        if ( $max_lines && count($lines)>$max_lines ) { $lines=array_slice($lines,0,$max_lines); $lines[$max_lines-1]=rtrim($lines[$max_lines-1],'. ').'...'; }
        foreach ( $lines as $i=>$line_text ) { $this->text($x,$y-($i*$line_height),$line_text,$size,$bold); }
        return $y-(count($lines)*$line_height);
    }

    public function set_y( $y ) { $this->y=(float)$y; }
    public function ensure_space( $height ) { if ( $this->y-$height < 48 ) { $this->new_page(); return true; } return false; }

    /**
     * Return the current site's display name for report branding.
     *
     * @return string
     */
    private function site_name() {
        if ( null !== $this->site_name_cache ) {
            return $this->site_name_cache;
        }
        $name = function_exists( 'get_bloginfo' ) ? (string) get_bloginfo( 'name' ) : '';
        $name = trim( wp_strip_all_tags( $name ) );
        $this->site_name_cache = '' !== $name ? $name : $this->footer_label;
        return $this->site_name_cache;
    }

    /**
     * Convert a local attachment image to a small JPEG for the PDF engine.
     *
     * @param string $source Local file path.
     * @return array|false
     */
    private function local_image_as_jpeg( $source ) {
        if ( ! is_string( $source ) || '' === $source || ! is_readable( $source ) || ! function_exists( 'wp_get_image_editor' ) ) {
            return false;
        }
        $editor = wp_get_image_editor( $source );
        if ( is_wp_error( $editor ) ) {
            return false;
        }
        $size = $editor->get_size();
        if ( is_array( $size ) && ( (int) $size['width'] > 240 || (int) $size['height'] > 240 ) ) {
            $editor->resize( 240, 240, false );
        }
        $tmp = wp_tempnam( 'ilsm-pdf-site-logo.jpg' );
        if ( ! $tmp ) {
            return false;
        }
        $saved = $editor->save( $tmp, 'image/jpeg' );
        if ( is_wp_error( $saved ) || empty( $saved['path'] ) || ! is_readable( $saved['path'] ) ) {
            if ( file_exists( $tmp ) ) { wp_delete_file( $tmp ); }
            return false;
        }
        $data = file_get_contents( $saved['path'] ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local temporary image generated by WordPress.
        $info = false !== $data ? @getimagesizefromstring( $data ) : false; // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged -- Invalid image conversion is handled by the fallback.
        wp_delete_file( $saved['path'] );
        if ( $saved['path'] !== $tmp && file_exists( $tmp ) ) {
            wp_delete_file( $tmp );
        }
        if ( ! is_string( $data ) || ! is_array( $info ) || IMAGETYPE_JPEG !== (int) $info[2] ) {
            return false;
        }
        return array( 'data' => $data, 'width' => (int) $info[0], 'height' => (int) $info[1] );
    }

    /**
     * Return the website logo (custom logo first, site icon second) as JPEG.
     * Falls back to the bundled plugin icon only when the site has no usable logo.
     *
     * @return array|false
     */
    private function site_logo_jpeg() {
        if ( null !== $this->site_logo_cache ) {
            return $this->site_logo_cache;
        }
        $this->site_logo_cache = false;
        $attachment_ids = array();
        if ( function_exists( 'get_theme_mod' ) ) {
            $custom_logo = absint( get_theme_mod( 'custom_logo', 0 ) );
            if ( $custom_logo ) { $attachment_ids[] = $custom_logo; }
        }
        $site_icon = absint( get_option( 'site_icon', 0 ) );
        if ( $site_icon ) { $attachment_ids[] = $site_icon; }
        foreach ( array_unique( $attachment_ids ) as $attachment_id ) {
            $path = get_attached_file( $attachment_id );
            $jpeg = $this->local_image_as_jpeg( $path );
            if ( $jpeg ) {
                $this->site_logo_cache = $jpeg;
                return $this->site_logo_cache;
            }
        }
        $this->site_logo_cache = $this->brand_logo_jpeg();
        return $this->site_logo_cache;
    }

    /**
     * Return the bundled plugin icon as a JPEG suitable for the lightweight PDF engine.
     *
     * The source remains admin/images/icon-40.png. Conversion is performed locally
     * through WordPress' image editor and cached only for this request.
     *
     * @return array|false Array with data, width and height, or false on failure.
     */
    private function brand_logo_jpeg() {
        if ( null !== $this->brand_logo_cache ) {
            return $this->brand_logo_cache;
        }

        $this->brand_logo_cache = false;
        if ( ! defined( 'ILSM_PATH' ) || ! function_exists( 'wp_get_image_editor' ) || ! function_exists( 'wp_tempnam' ) ) {
            return false;
        }

        $source = ILSM_PATH . 'admin/images/icon-40.png';
        if ( ! is_readable( $source ) ) {
            return false;
        }

        $editor = wp_get_image_editor( $source );
        if ( is_wp_error( $editor ) ) {
            return false;
        }

        $tmp = wp_tempnam( 'ilsm-pdf-logo.jpg' );
        if ( ! $tmp ) {
            return false;
        }

        $saved = $editor->save( $tmp, 'image/jpeg' );
        if ( is_wp_error( $saved ) || empty( $saved['path'] ) || ! is_readable( $saved['path'] ) ) {
            if ( file_exists( $tmp ) ) { wp_delete_file( $tmp ); }
            return false;
        }

        $data = file_get_contents( $saved['path'] ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local plugin-generated temporary image, no remote request.
        $info = false !== $data ? @getimagesizefromstring( $data ) : false; // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged -- Invalid conversion is handled by the fallback icon.
        wp_delete_file( $saved['path'] );
        if ( $saved['path'] !== $tmp && file_exists( $tmp ) ) {
            wp_delete_file( $tmp );
        }

        if ( ! is_string( $data ) || ! is_array( $info ) || IMAGETYPE_JPEG !== (int) $info[2] ) {
            return false;
        }

        $this->brand_logo_cache = array(
            'data'   => $data,
            'width'  => (int) $info[0],
            'height' => (int) $info[1],
        );
        return $this->brand_logo_cache;
    }

    public function report_header( $report_title, $site_url, $scan_label, $generated_label = '' ) {
        // Premium site-first report identity. The plugin is intentionally secondary.
        $this->rect( 0, 728, $this->page_width, 114, 8, 25, 50 );
        $this->rect( 0, 728, $this->page_width, 4, 37, 99, 235 );
        $this->rect( 0, 732, $this->page_width, 2, 20, 184, 166 );

        $logo = $this->site_logo_jpeg();
        $this->rounded_rect( 30, 774, 50, 50, 12, array( 255, 255, 255 ), null );
        if ( $logo ) {
            $iw = (float) $logo['width']; $ih = (float) $logo['height'];
            $ratio = min( 42 / max( 1, $iw ), 42 / max( 1, $ih ) );
            $dw = max( 1, $iw * $ratio ); $dh = max( 1, $ih * $ratio );
            $this->jpeg_image( $logo['data'], $logo['width'], $logo['height'], 34 + ( 42 - $dw ) / 2, 778 + ( 42 - $dh ) / 2, $dw, $dh );
        }

        $site_name = $this->site_name();
        $this->set_color( 255, 255, 255 );
        $this->text( 94, 805, $this->shorten( $site_name, 41 ), 16.5, true );
        $this->set_color( 219, 234, 254 );
        $this->text( 94, 783, $report_title, 11 );
        $this->set_color( 148, 163, 184 );
        $this->text( 94, 765, __( 'Website link intelligence report', 'dma-internlink-mapper' ), 7 );

        // Compact provenance/status panel at the right.
        $this->rounded_rect( 397, 757, 164, 62, 8, array( 15, 39, 71 ), array( 51, 65, 85 ) );
        $this->set_color( 186, 230, 253 );
        $this->text( 409, 804, __( 'REPORT DETAILS', 'dma-internlink-mapper' ), 6.3, true );
        $this->set_color( 241, 245, 249 );
        $this->text( 409, 790, $this->shorten( $scan_label, 32 ), 6.5, true );
        if ( $generated_label ) { $this->text( 409, 777, $this->shorten( $generated_label, 32 ), 6.1 ); }
        $this->set_color( 148, 163, 184 );
        $this->text( 409, 764, $this->shorten( preg_replace( '#^https?://#', '', (string) $site_url ), 34 ), 5.9 );

        // Subtle local-generation badge.
        $this->rounded_rect( 30, 740, 146, 16, 6, array( 30, 41, 59 ), null );
        $this->set_color( 167, 243, 208 );
        $this->text( 39, 746, __( 'LOCAL SCAN - NO EXTERNAL REPORT SERVICE', 'dma-internlink-mapper' ), 5.2, true );
        $this->set_y( 704 );
    }

    public function heading( $title, $subtitle = '' ) {
        $this->ensure_space(60); $this->set_color(79,70,229); $this->text($this->margin,$this->y,strtoupper($title),10,true); $this->y-=18;
        if($subtitle){$this->set_color(71,85,105); $this->y=$this->wrapped_text($this->margin,$this->y,$subtitle,105,8,11,false,3);}
        $this->y-=7;
    }

    public function metric_card( $x, $y, $w, $label, $value, $note, $accent ) {
        $this->rounded_rect($x,$y,$w,68,8,array(255,255,255),array(226,232,240));
        $this->rounded_rect($x+10,$y+38,24,20,5,array($accent[0],$accent[1],$accent[2]),null);
        $this->set_color(71,85,105); $this->text($x+42,$y+48,$label,7.2,true);
        $this->set_color(15,23,42); $this->text($x+42,$y+27,(string)$value,15,true);
        $this->set_color(100,116,139); $this->text($x+10,$y+10,$this->shorten($note,30),6.3);
    }

    public function stat_box( $x,$y,$w,$label,$value,$accent=array(79,70,229) ) {
        $this->rounded_rect($x,$y,$w,48,7,array(248,250,252),array(226,232,240));
        $this->set_color($accent[0],$accent[1],$accent[2]); $this->text($x+10,$y+30,(string)$value,13,true);
        $this->set_color(71,85,105); $this->text($x+10,$y+12,$this->shorten($label,26),6.7);
    }

    private function table_header( $headers, $widths, $font_size ) {
        $row_height=22; $x=$this->margin; $this->rect($x,$this->y-$row_height,array_sum($widths),$row_height,15,39,71);
        $this->set_color(255,255,255); foreach($headers as $i=>$header){$this->text($x+5,$this->y-14,$header,max(6.2,$font_size),true);$x+=$widths[$i];}
        $this->y-=$row_height;
    }

    public function table( $headers, $rows, $widths, $font_size = 7.2 ) {
        $row_height=22; $this->ensure_space($row_height*2); $this->table_header($headers,$widths,$font_size);
        foreach($rows as $row_index=>$row){
            if($this->y-$row_height<45){$this->new_page();$this->table_header($headers,$widths,$font_size);}
            $x=$this->margin; $bg=0===$row_index%2?array(248,250,252):array(255,255,255); $this->rect($x,$this->y-$row_height,array_sum($widths),$row_height,$bg[0],$bg[1],$bg[2]);
            $this->set_color(30,41,59);
            foreach($headers as $i=>$unused){$value=isset($row[$i])?(string)$row[$i]:'';$max=max(5,(int)floor($widths[$i]/($font_size*.49)));if(strlen($value)>$max){$value=substr($value,0,max(1,$max-3)).'...';}$this->text($x+5,$this->y-14,$value,$font_size);$x+=$widths[$i];}
            $this->line($this->margin,$this->y-$row_height,$this->margin+array_sum($widths),$this->y-$row_height,226,232,240,.35); $this->y-=$row_height;
        }
        $this->y-=10;
    }

    public function graph_snapshot( $nodes, $edges, $x, $y, $w, $h, $selected_id = 0 ) {
        $this->rounded_rect($x,$y,$w,$h,8,array(250,252,255),array(226,232,240));
        if(!$nodes){$this->set_color(100,116,139);$this->text($x+16,$y+$h/2,'No internal graph data in this scan.',8);return;}
        $cx=$x+$w/2;$cy=$y+$h/2;$count=count($nodes);$positions=array();
        foreach(array_values($nodes) as $i=>$n){$angle=2*M_PI*$i/max(1,$count);$ring=($i%3)/3;$radius=min($w,$h)*(.22+.20*$ring);$positions[(int)$n['post_id']]=array($cx+cos($angle)*$radius,$cy+sin($angle)*$radius);}
        foreach($edges as $e){$s=(int)$e['source_post_id'];$t=(int)$e['target_post_id'];if(!isset($positions[$s],$positions[$t]))continue;$a=$positions[$s];$b=$positions[$t];$this->line($a[0],$a[1],$b[0],$b[1],203,213,225,.28);}
        foreach($nodes as $n){$id=(int)$n['post_id'];$p=$positions[$id];$incoming=(int)$n['incoming_count'];$r=max(3,min(8,3+sqrt(max(0,$incoming))*.45));$is_sel=$selected_id&&$id===(int)$selected_id;$is_orphan=!empty($n['is_orphan']);$c=$is_sel?array(124,58,237):($is_orphan?array(239,68,68):((int)$n['seo_score']>=75?array(16,185,129):array(37,99,235)));$this->filled_circle($p[0],$p[1],$r,$c[0],$c[1],$c[2]);}
    }

    public function shorten($value,$max){$value=$this->esc($value);return strlen($value)>$max?substr($value,0,max(1,$max-3)).'...':$value;}


    public function pill( $x, $y, $text, $fill = array( 220, 252, 231 ), $color = array( 22, 101, 52 ), $w = 0 ) {
        $w = $w ? (float) $w : max( 34, min( 120, 8 + strlen( $this->esc( $text ) ) * 3.8 ) );
        $this->rounded_rect( $x, $y, $w, 15, 5, $fill, array( 209, 213, 219 ) );
        $this->set_color( $color[0], $color[1], $color[2] );
        $this->text( $x + 5, $y + 5, $text, 5.9, true );
    }

    public function icon_metric( $x, $y, $w, $label, $value, $accent = array( 37, 99, 235 ), $icon = '●' ) {
        $this->rounded_rect( $x, $y, $w, 56, 8, array( 255, 255, 255 ), array( 226, 232, 240 ) );
        $this->rounded_rect( $x + 10, $y + 29, 24, 20, 6, array( max( 235, $accent[0] ), max( 238, $accent[1] ), max( 245, $accent[2] ) ), null );
        $this->set_color( $accent[0], $accent[1], $accent[2] );
        $this->text( $x + 17, $y + 35, $icon, 8, true );
        $this->set_color( 71, 85, 105 );
        $this->text( $x + 42, $y + 38, $label, 6.5, true );
        $this->set_color( 15, 23, 42 );
        $this->text( $x + 42, $y + 17, (string) $value, 13, true );
    }

    public function donut_chart( $cx, $cy, $radius, $segments, $center_top = '', $center_bottom = '' ) {
        $total = 0;
        foreach ( $segments as $seg ) { $total += max( 0, (float) $seg[0] ); }
        if ( $total <= 0 ) { $segments = array( array( 1, array( 226, 232, 240 ), 'None' ) ); $total = 1; }
        $this->circle( $cx, $cy, $radius, 226, 232, 240, 13 );
        $start = 90.0;
        foreach ( $segments as $seg ) {
            $value = max( 0, (float) $seg[0] );
            if ( $value <= 0 ) { continue; }
            $color = $seg[1];
            $steps = max( 1, (int) round( 96 * $value / $total ) );
            $this->set_color( $color[0], $color[1], $color[2], true );
            $this->content .= "13 w 1 J\n";
            for ( $i = 0; $i < $steps; $i++ ) {
                $a1 = deg2rad( $start - ( $i * 360 / 96 ) );
                $a2 = deg2rad( $start - ( ( $i + 0.82 ) * 360 / 96 ) );
                $x1 = $cx + $radius * cos( $a1 ); $y1 = $cy + $radius * sin( $a1 );
                $x2 = $cx + $radius * cos( $a2 ); $y2 = $cy + $radius * sin( $a2 );
                $this->content .= sprintf( "%.2F %.2F m %.2F %.2F l S\n", $x1, $y1, $x2, $y2 );
            }
            $start -= 360 * $value / $total;
        }
        if ( $center_top ) { $this->set_color( 15, 23, 42 ); $this->text( $cx - ( strlen( $center_top ) * 3.4 ), $cy + 2, $center_top, 13, true ); }
        if ( $center_bottom ) { $this->set_color( 71, 85, 105 ); $this->text( $cx - ( strlen( $center_bottom ) * 2.3 ), $cy - 14, $center_bottom, 6.2, true ); }
    }

    public function legend_item( $x, $y, $label, $value, $color ) {
        $this->filled_circle( $x, $y + 3, 3.5, $color[0], $color[1], $color[2] );
        $this->set_color( 15, 23, 42 );
        $this->text( $x + 10, $y + 3, $this->shorten( $label, 24 ), 6.1, true );
        $this->set_color( 71, 85, 105 );
        $this->text( $x + 10, $y - 8, (string) $value, 5.8 );
    }

    public function horizontal_bars( $x, $y, $w, $rows, $max_value = 0 ) {
        if ( ! $max_value ) { foreach ( $rows as $row ) { $max_value = max( $max_value, (float) $row[1] ); } }
        $max_value = max( 1, (float) $max_value );
        foreach ( $rows as $idx => $row ) {
            $label = (string) $row[0]; $value = (float) $row[1]; $color = isset( $row[2] ) ? $row[2] : array( 37, 99, 235 );
            $yy = $y - ( $idx * 20 );
            $this->set_color( 15, 23, 42 ); $this->text( $x, $yy + 5, $this->shorten( $label, 8 ), 6, true );
            $this->rect( $x + 20, $yy, $w - 52, 8, 241, 245, 249 );
            $this->rect( $x + 20, $yy, max( 2, ( $w - 52 ) * min( 1, $value / $max_value ) ), 8, $color[0], $color[1], $color[2] );
            $this->set_color( 15, 23, 42 ); $this->text( $x + $w - 26, $yy + 1, number_format_i18n( $value ), 6 );
        }
    }

    public function score_list( $x, $y, $rows ) {
        foreach ( $rows as $idx => $row ) {
            $yy = $y - ( $idx * 24 );
            $color = $row[1] >= 90 ? array( 22, 163, 74 ) : ( $row[1] >= 80 ? array( 22, 163, 74 ) : ( $row[1] >= 65 ? array( 217, 119, 6 ) : array( 220, 38, 38 ) ) );
            $this->filled_circle( $x, $yy + 3, 4, $color[0], $color[1], $color[2] );
            $this->set_color( 15, 23, 42 ); $this->text( $x + 12, $yy + 1, $this->shorten( $row[0], 30 ), 6.4, true );
            $this->set_color( $color[0], $color[1], $color[2] ); $this->text( $x + 112, $yy + 1, (string) $row[1] . '/100', 6.4, true );
            $this->line( $x, $yy - 8, $x + 145, $yy - 8, 226, 232, 240, .35 );
        }
    }

    public function output( $filename ) {
        if ( '' !== $this->content ) { $this->pages[] = $this->content; }

        $objects = array();
        $objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
        $objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
        $objects[4] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';

        $next_object = 5;
        $image_objects = array();
        foreach ( $this->images as $image_index => $image ) {
            $image_objects[ $image_index ] = $next_object;
            $objects[ $next_object ] = '<< /Type /XObject /Subtype /Image /Width ' . (int) $image['width'] . ' /Height ' . (int) $image['height'] . ' /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ' . strlen( $image['data'] ) . ">>\nstream\n" . $image['data'] . "\nendstream";
            $next_object++;
        }

        $page_objects = array();
        foreach ( $this->pages as $page_index => $stream ) {
            $page_number = $page_index + 1;
            $page_object = $next_object++;
            $content_object = $next_object++;
            $page_objects[] = $page_object . ' 0 R';

            $xobjects = '';
            if ( ! empty( $this->page_images[ $page_number ] ) ) {
                $refs = array();
                foreach ( $this->page_images[ $page_number ] as $image_index ) {
                    if ( isset( $image_objects[ $image_index ], $this->images[ $image_index ] ) ) {
                        $refs[] = '/' . $this->images[ $image_index ]['name'] . ' ' . $image_objects[ $image_index ] . ' 0 R';
                    }
                }
                if ( $refs ) { $xobjects = ' /XObject << ' . implode( ' ', $refs ) . ' >>'; }
            }

            $objects[ $page_object ] = '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ' . $this->page_width . ' ' . $this->page_height . '] /Resources << /Font << /F1 3 0 R /F2 4 0 R >>' . $xobjects . ' >> /Contents ' . $content_object . ' 0 R >>';
            $objects[ $content_object ] = '<< /Length ' . strlen( $stream ) . ">>\nstream\n" . $stream . "endstream";
        }
        $objects[2] = '<< /Type /Pages /Kids [' . implode( ' ', $page_objects ) . '] /Count ' . count( $this->pages ) . ' >>';
        ksort( $objects, SORT_NUMERIC );

        $out = "%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";
        $offsets = array( 0 => 0 );
        $max_object = max( array_keys( $objects ) );
        for ( $i = 1; $i <= $max_object; $i++ ) {
            if ( ! isset( $objects[ $i ] ) ) { continue; }
            $offsets[ $i ] = strlen( $out );
            $out .= $i . " 0 obj\n" . $objects[ $i ] . "\nendobj\n";
        }
        $xref = strlen( $out );
        $out .= "xref\n0 " . ( $max_object + 1 ) . "\n0000000000 65535 f \n";
        for ( $i = 1; $i <= $max_object; $i++ ) {
            $out .= isset( $offsets[ $i ] ) ? sprintf( "%010d 00000 n \n", $offsets[ $i ] ) : "0000000000 00000 f \n";
        }
        $out .= 'trailer << /Size ' . ( $max_object + 1 ) . " /Root 1 0 R >>\nstartxref\n" . $xref . "\n%%EOF";
        nocache_headers();
        header( 'Content-Type: application/pdf' );
        header( 'Content-Disposition: attachment; filename="' . sanitize_file_name( $filename ) . '"' );
        header( 'Content-Length: ' . strlen( $out ) );
        echo $out; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Binary PDF output.
        exit;
    }
}
