<?php
/**
 * Admin asset registration and localized runtime data.
 *
 * @package Internal_Link_SEO_Mapper
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

final class ILSM_Admin_Assets {
    /** Register hooks. */
    public static function register() {
        add_action( 'admin_enqueue_scripts', array( __CLASS__, 'enqueue' ) );
    }

    public static function enqueue( $hook ) {
        if ( false === strpos( $hook, 'ilsm-' ) ) { return; }

        wp_enqueue_style( 'ilsm-font-awesome', ILSM_URL . 'admin/vendor/font-awesome/css/font-awesome.min.css', array(), '4.7.0' );
        $admin_css = ILSM_PATH . 'admin/css/admin.css';
        $admin_js = ILSM_PATH . 'admin/js/admin.js';
        $map_js = ILSM_PATH . 'admin/js/map-interactions.js';
        // A content-derived version prevents an older admin bundle from being
        // reused after a ZIP update whose extracted file timestamps happen to
        // match the previous release. This is important for long-running AJAX
        // workflows where stale JavaScript and current PHP cannot interoperate.
        $admin_css_version = is_readable( $admin_css ) ? substr( hash_file( 'sha256', $admin_css ), 0, 12 ) : ILSM_VERSION;
        $admin_js_version  = is_readable( $admin_js ) ? substr( hash_file( 'sha256', $admin_js ), 0, 12 ) : ILSM_VERSION;
        wp_enqueue_style( 'ilsm-admin', ILSM_URL . 'admin/css/admin.css', array( 'ilsm-font-awesome' ), $admin_css_version );
        $onpage_css = ILSM_PATH . 'admin/css/onpage-audit.css';
        if ( false !== strpos( $hook, 'ilsm-on-page-seo' ) && is_readable( $onpage_css ) ) {
            wp_enqueue_style( 'ilsm-onpage-audit', ILSM_URL . 'admin/css/onpage-audit.css', array( 'ilsm-admin' ), (string) filemtime( $onpage_css ) );
        }
        wp_enqueue_script( 'ilsm-admin', ILSM_URL . 'admin/js/admin.js', array( 'jquery' ), $admin_js_version, true );
        if ( false !== strpos( $hook, 'ilsm-visual-map' ) && is_readable( $map_js ) ) {
            wp_enqueue_script( 'ilsm-map-interactions', ILSM_URL . 'admin/js/map-interactions.js', array( 'ilsm-admin' ), (string) filemtime( $map_js ), true );
        }

        $settings = get_option( 'ilsm_settings', array() );
        global $wpdb;
        // phpcs:ignore PluginCheck.Security.DirectDB.UnescapedDBParameter,WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching -- Dynamic identifiers are produced by the strict ILSM_Database allowlist. Plugin-owned custom tables require direct database access. Mutable scan data must be read fresh; persistent object caching would be stale.
        $current_scan = $wpdb->get_row( "SELECT id,user_id,status,scanned_items,total_items,lock_expires,heartbeat_at,started_at FROM " . ILSM_Database::table( 'scans' ) . " WHERE status IN ('running','paused','interrupted') ORDER BY id DESC LIMIT 1", ARRAY_A ); // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared,WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching,PluginCheck.Security.DirectDB.UnescapedDBParameter -- Plugin-owned custom tables require direct SQL; identifiers are generated from a strict internal allowlist, mutable scan state must not be cached, and generated placeholders are completed with validated integer arguments.
        wp_localize_script( 'ilsm-admin', 'ILSM', array(
            'ajax'      => admin_url( 'admin-ajax.php' ),
            'nonce'     => wp_create_nonce( 'ilsm_admin' ),
            'insertNonce' => wp_create_nonce( 'ilsm_insert_links' ),
            'externalNonce' => wp_create_nonce( 'ilsm_external_links' ),
            'brokenNonce' => wp_create_nonce( 'ilsm_broken_links' ),
            'visualPdfUrl' => admin_url( 'admin-post.php' ),
            'visualPdfNonce' => wp_create_nonce( 'ilsm_export_visual_pdf' ),
            'knowledgePageExportBase' => wp_nonce_url( admin_url( 'admin-post.php?action=ilsm_export_knowledge_pdf&scope=page' ), 'ilsm_export_knowledge_pdf' ),
            'defaultTheme' => in_array( (string) ( $settings['admin_theme'] ?? 'dark' ), array( 'dark', 'light', 'system' ), true ) ? (string) ( $settings['admin_theme'] ?? 'dark' ) : 'dark',
            'delay'     => (int) ( $settings['batch_delay'] ?? 350 ),
            'currentScan' => $current_scan ?: null,
            'canForceUnlock' => current_user_can( 'ilsm_manage_settings' ),
            'canManageSettings' => current_user_can( 'ilsm_manage_settings' ),
            'settingsUrl'  => admin_url( 'admin.php?page=ilsm-settings#ilsm-safe-link-insertion' ),
            'dashboardUrl' => admin_url( 'admin.php?page=ilsm-dashboard' ),
            'mapColors' => array(
                'incoming' => sanitize_hex_color( $settings['incoming_color'] ?? '#2563EB' ) ?: '#2563EB',
                'outgoing' => sanitize_hex_color( $settings['outgoing_color'] ?? '#F97316' ) ?: '#F97316',
                'external' => '#AC2174',
                'broken'   => sanitize_hex_color( $settings['broken_color'] ?? '#EF4444' ) ?: '#EF4444',
                'redirect' => sanitize_hex_color( $settings['redirect_color'] ?? '#8B5CF6' ) ?: '#8B5CF6',
            ),
            'strings'   => array(
                'scanRequestFailed' => __( 'The scan request failed. Checking the current server state.', 'dma-internlink-mapper' ),
                'brokenChecking' => __( 'Checking…', 'dma-internlink-mapper' ),
                'brokenRequestFailed' => __( 'Request failed. Reload the page and try again.', 'dma-internlink-mapper' ),
                'brokenInvalidResponse' => __( 'The server returned an invalid response.', 'dma-internlink-mapper' ),
                'brokenSelectOne' => __( 'Select at least one verified 404 link.', 'dma-internlink-mapper' ),
                'brokenEnterUrl' => __( 'Enter the new destination URL.', 'dma-internlink-mapper' ),
                'brokenConfirmSuffix' => __( 'selected link(s)? Content edits create revisions; redirects affect all requests to the old URL.', 'dma-internlink-mapper' ),
                'brokenApplying' => __( 'Verifying and applying reviewed SEO repairs…', 'dma-internlink-mapper' ),
                'confirmStop' => __( 'Cancel the current scan?', 'dma-internlink-mapper' ),
                'noData'      => __( 'No completed scan data is available yet.', 'dma-internlink-mapper' ),
                'confirmUnlock' => __( 'Force-unlock the scan? Use this only when no scan is actually running.', 'dma-internlink-mapper' ),
                'confirmFirstScan' => __( 'Start your first website scan?', 'dma-internlink-mapper' ),
                'confirmRescan'    => __( 'Start a fresh scan? Any currently running scan owned by you will be cancelled, while previous completed report data remains available.', 'dma-internlink-mapper' ),
                'copied'           => __( 'Copied', 'dma-internlink-mapper' ),
                'copyUrl'          => __( 'Copy URL', 'dma-internlink-mapper' ),
                'copyPrompt'       => __( 'Copy this URL:', 'dma-internlink-mapper' ),
                'totalPages'        => __( 'Total pages', 'dma-internlink-mapper' ),
                'levels'            => __( 'Levels', 'dma-internlink-mapper' ),
                'orphanPages'       => __( 'Orphan pages', 'dma-internlink-mapper' ),
                'internalLinks'     => __( 'Internal links', 'dma-internlink-mapper' ),
                'brokenLinks'       => __( 'Broken links', 'dma-internlink-mapper' ),
                'architectureHealth'=> __( 'Architecture health', 'dma-internlink-mapper' ),
                'totalInternalLinks'=> __( 'Total internal links', 'dma-internlink-mapper' ),
                'totalLevels'       => __( 'Total levels', 'dma-internlink-mapper' ),
                'averageDepth'      => __( 'Average depth', 'dma-internlink-mapper' ),
                'maximumDepth'      => __( 'Maximum depth', 'dma-internlink-mapper' ),
                'pagesWithoutChildren' => __( 'Pages without children', 'dma-internlink-mapper' ),
                'pagesWithoutOutgoing' => __( 'Pages without outgoing', 'dma-internlink-mapper' ),
                'postType'          => __( 'Post type', 'dma-internlink-mapper' ),
                'incomingLinks'     => __( 'Incoming links', 'dma-internlink-mapper' ),
                'outgoingLinks'     => __( 'Outgoing links', 'dma-internlink-mapper' ),
                'children'          => __( 'Children', 'dma-internlink-mapper' ),
                'seoScore'          => __( 'SEO score', 'dma-internlink-mapper' ),
                'editPage'          => __( 'Edit page', 'dma-internlink-mapper' ),
                'viewPage'          => __( 'View page', 'dma-internlink-mapper' ),
                'openLinkMap'       => __( 'Open in Link Map', 'dma-internlink-mapper' ),
                'linkOpportunities' => __( 'Link Opportunities', 'dma-internlink-mapper' ),
                'healthAudit'       => __( 'Health Audit', 'dma-internlink-mapper' ),
                'orphan'            => __( 'Orphan', 'dma-internlink-mapper' ),
                'level'             => __( 'Level', 'dma-internlink-mapper' ),
                'relationship'      => __( 'Relationship', 'dma-internlink-mapper' ),
                'scanFailed' => __( 'Scan failed.', 'dma-internlink-mapper' ),
                'scanCompleted' => __( 'Scan completed successfully.', 'dma-internlink-mapper' ),
                /* translators: %s: Current retry attempt number. */
                'retryingBatch' => __( 'Retrying stalled batch (%s/3)…', 'dma-internlink-mapper' ),
                'scanTimeout' => __( 'Scan batch timed out after 30 seconds. Checking the server before another batch starts.', 'dma-internlink-mapper' ),
                'checkingScanState' => __( 'Checking current scan state…', 'dma-internlink-mapper' ),
                'finishingCurrentBatch' => __( 'Finishing current batch…', 'dma-internlink-mapper' ),
                'scanStateUnknown' => __( 'Scan state could not be confirmed', 'dma-internlink-mapper' ),
                'scanStateUnknownHelp' => __( 'The browser could not confirm the scan state. No new batch was started.', 'dma-internlink-mapper' ),
                'runningOtherSession' => __( 'Running in another browser session', 'dma-internlink-mapper' ),
                'completed' => __( 'Completed', 'dma-internlink-mapper' ),
                'startingFreshScan' => __( 'Starting fresh scan…', 'dma-internlink-mapper' ),
                'couldNotStartScan' => __( 'Could not start scan.', 'dma-internlink-mapper' ),
                'freshScanStarted' => __( 'Fresh scan started.', 'dma-internlink-mapper' ),
                'startSessionScan' => __( 'Start a scan in this browser session first.', 'dma-internlink-mapper' ),
                'actionFailed' => __( 'Action failed.', 'dma-internlink-mapper' ),
                'unlockFailed' => __( 'Unlock failed.', 'dma-internlink-mapper' ),
                'scanCleared' => __( 'Interrupted scan cleared. You can run a fresh rescan.', 'dma-internlink-mapper' ),
                'running' => __( 'Running', 'dma-internlink-mapper' ),
                'paused' => __( 'Paused', 'dma-internlink-mapper' ),
                'cancelled' => __( 'Cancelled', 'dma-internlink-mapper' ),
                'interrupted' => __( 'Interrupted', 'dma-internlink-mapper' ),
                'starting' => __( 'Starting…', 'dma-internlink-mapper' ),
                'incoming' => __( 'Incoming', 'dma-internlink-mapper' ),
                'outgoing' => __( 'Outgoing', 'dma-internlink-mapper' ),
                'weakAnchors' => __( 'Weak anchors', 'dma-internlink-mapper' ),
                /* translators: %s: SEO score value. */
                'seoScoreOutOf' => __( 'SEO score: %s out of 100', 'dma-internlink-mapper' ),
                'hasIncoming' => __( 'Page has incoming internal links.', 'dma-internlink-mapper' ),
                'addIncoming' => __( 'Add at least one relevant incoming link.', 'dma-internlink-mapper' ),
                'outgoingHealthy' => __( 'Outgoing link coverage is healthy.', 'dma-internlink-mapper' ),
                'addOutgoing' => __( 'Add useful contextual outgoing links.', 'dma-internlink-mapper' ),
                'anchorsDescriptive' => __( 'Anchor text is descriptive.', 'dma-internlink-mapper' ),
                'replaceGenericAnchor' => __( 'Replace generic or empty anchor text.', 'dma-internlink-mapper' ),
                'runCompletedScan' => __( 'Run a completed scan to calculate evidence for this page.', 'dma-internlink-mapper' ),
                'contextualIncoming' => __( 'Contextual incoming', 'dma-internlink-mapper' ),
                'uniqueSourcePages' => __( 'Unique source pages', 'dma-internlink-mapper' ),
                'uniqueAnchors' => __( 'Unique anchors', 'dma-internlink-mapper' ),
                'peerAvgIncoming' => __( 'Peer avg. incoming', 'dma-internlink-mapper' ),
                'loadThisMap' => __( 'Load this map', 'dma-internlink-mapper' ),
                'anchorText' => __( 'Anchor text', 'dma-internlink-mapper' ),
                'postId' => __( 'Post ID', 'dma-internlink-mapper' ),
                'mapClickHelp' => __( 'Single click shows details. Double click opens the selected page map.', 'dma-internlink-mapper' ),
                'noScanPage' => __( 'No scan data is available for this page.', 'dma-internlink-mapper' ),
                'nextStep' => __( 'Next step', 'dma-internlink-mapper' ),
                'enablePostTypeRescan' => __( 'Enable this post type and run a fresh full scan.', 'dma-internlink-mapper' ),
                'mapLoadFailed' => __( 'Map could not be loaded.', 'dma-internlink-mapper' ),
                'mapRequestFailed' => __( 'Map request failed.', 'dma-internlink-mapper' ),
                'nonWpNode' => __( 'This node is external, an archive, a taxonomy, or unresolved. It has no WordPress page link map.', 'dma-internlink-mapper' ),
                'opportunityGenerationFailed' => __( 'Opportunity generation failed.', 'dma-internlink-mapper' ),
                'generationRequestFailed' => __( 'The generation request failed.', 'dma-internlink-mapper' ),
                'opportunityStatusFailed' => __( 'The opportunity status could not be updated.', 'dma-internlink-mapper' ),
                'opportunityStatusRequestFailed' => __( 'The opportunity status request failed.', 'dma-internlink-mapper' ),
                'alreadyLinked' => __( 'Already linked', 'dma-internlink-mapper' ),
                'newOpportunity' => __( 'New opportunity', 'dma-internlink-mapper' ),
                'openSource' => __( 'Open source', 'dma-internlink-mapper' ),
                'wooExcluded' => __( 'WooCommerce cart, checkout, account, login and thank-you URLs are excluded automatically.', 'dma-internlink-mapper' ),
                'chooseDestination' => __( 'Choose a destination page or taxonomy URL first.', 'dma-internlink-mapper' ),
                'enterKeyword' => __( 'Enter a keyword or keyphrase for the destination.', 'dma-internlink-mapper' ),
                'searchingIndex' => __( 'Searching the local crawl index…', 'dma-internlink-mapper' ),
                'focusedSearchFailed' => __( 'The focused search failed.', 'dma-internlink-mapper' ),
                'focusedSearchRequestFailed' => __( 'The focused search request failed.', 'dma-internlink-mapper' ),
                'noFocusedOpportunities' => __( 'No safe body-text opportunities were found for this destination and keyword.', 'dma-internlink-mapper' ),
                'resetDefaultsConfirm' => __( 'Reset these fields to the plugin defaults? Click Save Settings to apply them.', 'dma-internlink-mapper' ),
                'selectScannedPage' => __( 'Select a scanned page', 'dma-internlink-mapper' ),
                'searchContent' => __( 'Search pages, posts or trips', 'dma-internlink-mapper' ),
                'noMatchingContent' => __( 'No matching scanned content found.', 'dma-internlink-mapper' ),
                'dialogUnavailable' => __( 'The insertion dialog is unavailable. Reload this page and try again.', 'dma-internlink-mapper' ),
                'reviewPreview' => __( 'Review the proposed source, anchor, destination and insertion context. No content will be changed.', 'dma-internlink-mapper' ),
                'reviewLive' => __( 'Review the verified source, anchor and destination before writing the link.', 'dma-internlink-mapper' ),
                'source' => __( 'Source', 'dma-internlink-mapper' ),
                'destination' => __( 'Destination', 'dma-internlink-mapper' ),
                'insertLocation' => __( 'Insert location', 'dma-internlink-mapper' ),
                'editor' => __( 'Editor', 'dma-internlink-mapper' ),
                'confidence' => __( 'Confidence', 'dma-internlink-mapper' ),
                'required' => __( 'required', 'dma-internlink-mapper' ),
                'notInsertable' => __( 'Not currently insertable.', 'dma-internlink-mapper' ),
                'validationFailed' => __( 'This opportunity no longer passes validation.', 'dma-internlink-mapper' ),
                'enableLiveMode' => __( 'Enable Live Mode', 'dma-internlink-mapper' ),
                'previewModeEnabled' => __( 'Preview Mode is enabled', 'dma-internlink-mapper' ),
                'previewModeHelp' => __( 'No post content was changed. To write approved links, open Settings → Safe Link Insertion, clear Preview Mode, save the settings, then run Insert Selected Links again.', 'dma-internlink-mapper' ),
                'openInsertionSettings' => __( 'Open insertion settings', 'dma-internlink-mapper' ),
                'safetyPreviewFailed' => __( 'Safety preview failed.', 'dma-internlink-mapper' ),
                'safetyPreviewTimeout' => __( 'Safety preview timed out after 60 seconds.', 'dma-internlink-mapper' ),
                'preparingPreview' => __( 'Preparing insertion preview…', 'dma-internlink-mapper' ),
                'previewFailedChanged' => __( 'Preview failed. Regenerate opportunities if the source content has changed.', 'dma-internlink-mapper' ),
                'noLongerPassesChecks' => __( 'This opportunity no longer passes the current insertion checks.', 'dma-internlink-mapper' ),
                'waitingSafety' => __( 'Waiting for safety check…', 'dma-internlink-mapper' ),
                'checking' => __( 'Checking…', 'dma-internlink-mapper' ),
                'testing' => __( 'Testing…', 'dma-internlink-mapper' ),
                'inserting' => __( 'Inserting…', 'dma-internlink-mapper' ),
                'removeInsertedConfirm' => __( 'Remove only the inserted link markup and preserve the anchor text?', 'dma-internlink-mapper' ),
                'undone' => __( 'Undone', 'dma-internlink-mapper' ),
                'undoFailed' => __( 'Undo failed.', 'dma-internlink-mapper' ),
                'enableLiveConfirm' => __( 'Enable Live Mode? Future approved insertions will write links into content. Existing Preview results will not be inserted automatically.', 'dma-internlink-mapper' ),
                'enabling' => __( 'Enabling…', 'dma-internlink-mapper' ),
                'liveModeBadge' => __( 'Live Mode: links are written to content', 'dma-internlink-mapper' ),
                'liveModeEnabled' => __( 'Live Mode enabled', 'dma-internlink-mapper' ),
                'liveModeEnabledHelp' => __( 'Preview is now disabled. Approved links will be written and verified during the next insertion run.', 'dma-internlink-mapper' ),
                'analyzingRenderedHtml' => __( 'Analyzing rendered public HTML…', 'dma-internlink-mapper' ),
                'seoAnalysisFailed' => __( 'SEO analysis failed.', 'dma-internlink-mapper' ),
                'seoAnalysisRequestFailed' => __( 'SEO analysis request failed.', 'dma-internlink-mapper' ),
                'seoAnalysisTimeout' => __( 'SEO analysis timed out. The completed scan score remains unchanged; try again after page caching is available.', 'dma-internlink-mapper' ),
                'seoAnalysisRenderFailed' => __( 'The SEO breakdown could not be displayed. Reload this page and try again.', 'dma-internlink-mapper' ),
                /* translators: %s: Description of the selected bulk action. */
                'bulkActionConfirm' => __( 'Bulk action: %s? Each link is validated separately before WordPress changes any content.', 'dma-internlink-mapper' ),
                /* translators: %s: Number of selected external links. */
                'externalSelected' => __( '%s selected', 'dma-internlink-mapper' ),
                /* translators: %s: Number of external domains currently needing review. */
                'approveAllDomainsConfirm' => __( 'Approve all %s external domains currently needing review? This adds them to Approved domains.', 'dma-internlink-mapper' ),
                /* translators: %s: Number of selected external domains. */
                'approveSelectedDomainsConfirm' => __( 'Approve %s selected external domains? This adds them to Approved domains.', 'dma-internlink-mapper' ),
                'approvingDomains' => __( 'Approving domains…', 'dma-internlink-mapper' ),
                'domainsApproved' => __( 'Domains approved.', 'dma-internlink-mapper' ),
                'approveDomainsFailed' => __( 'The domains could not be approved.', 'dma-internlink-mapper' ),
                'dofollow' => __( 'Dofollow', 'dma-internlink-mapper' ),
                'nofollow' => __( 'Nofollow', 'dma-internlink-mapper' ),
                'setDofollow' => __( 'Set dofollow', 'dma-internlink-mapper' ),
                'setNofollow' => __( 'Set nofollow', 'dma-internlink-mapper' ),
                'removeNofollowOnly' => __( 'Remove only the nofollow token.', 'dma-internlink-mapper' ),
                'preserveRelValues' => __( 'Preserve other rel values.', 'dma-internlink-mapper' ),
                'bulkSetDofollowDescription' => __( 'set each selected link to dofollow by removing only the nofollow token', 'dma-internlink-mapper' ),
                'bulkSetNofollowDescription' => __( 'add nofollow to each selected link while preserving other rel values', 'dma-internlink-mapper' ),
                'bulkReplaceDescription' => __( 'replace each selected destination with [Removed Link]', 'dma-internlink-mapper' ),
                'bulkUnlinkDescription' => __( 'unlink each selected destination while preserving its anchor text', 'dma-internlink-mapper' ),
                /* translators: 1: Number of updated links, 2: Number of skipped or failed links. */
                'externalBulkFinished' => __( '%1$s updated · %2$s skipped/failed', 'dma-internlink-mapper' ),
                /* translators: 1: Number processed, 2: Total number, 3: Number skipped or failed. */
                'externalBulkProgress' => __( '%1$s / %2$s · %3$s skipped/failed', 'dma-internlink-mapper' ),
                'confirmSetNofollow' => __( 'Add nofollow to this external link? Other rel values such as sponsored, ugc, noopener and noreferrer are preserved.', 'dma-internlink-mapper' ),
                'confirmSetDofollow' => __( 'Set this external link to dofollow? Only the nofollow token is removed; other rel values are preserved.', 'dma-internlink-mapper' ),
                'domainSetAllNofollow' => __( 'add nofollow to all editable occurrences while preserving other rel values', 'dma-internlink-mapper' ),
                'domainSetAllDofollow' => __( 'remove only the nofollow token from all editable occurrences', 'dma-internlink-mapper' ),
                'domainUnlinkAll' => __( 'unlink all safely editable occurrences and keep their anchor text', 'dma-internlink-mapper' ),
                'domainReplaceAll' => __( 'replace all safely editable occurrences with [Removed Link]', 'dma-internlink-mapper' ),
                'domainIgnoreOccurrences' => __( 'hide the current scanned occurrences from this report without changing page content', 'dma-internlink-mapper' ),
                'domainIgnoreDomain' => __( 'hide this hostname across External Link Health reports without changing page content', 'dma-internlink-mapper' ),
                /* translators: 1: Domain name, 2: occurrence count, 3: action description. */
                'domainActionConfirm' => __( 'Apply to %1$s (%2$s current occurrences): %3$s? Each editable source is revalidated before WordPress changes content.', 'dma-internlink-mapper' ),
                'domainActionStarting' => __( 'Starting…', 'dma-internlink-mapper' ),
                'setAllNofollow' => __( 'Set all to nofollow', 'dma-internlink-mapper' ),
                'setAllDofollow' => __( 'Set all to dofollow', 'dma-internlink-mapper' ),
                'unlinkAllOccurrences' => __( 'Unlink all occurrences', 'dma-internlink-mapper' ),
                'replaceAllRemoved' => __( 'Replace all with [Removed Link]', 'dma-internlink-mapper' ),
                'ignoreCurrentOccurrences' => __( 'Ignore current occurrences', 'dma-internlink-mapper' ),
                'confirmOperation' => __( 'Confirm operation', 'dma-internlink-mapper' ),
                'confirmDestructiveOperation' => __( 'Confirm destructive operation', 'dma-internlink-mapper' ),
                /* translators: %s: Domain action label, such as Set all to nofollow. */
                'domainActionWorking' => __( '%s in progress', 'dma-internlink-mapper' ),
                'currentOccurrences' => __( 'current occurrences', 'dma-internlink-mapper' ),
                'processing' => __( 'Processing', 'dma-internlink-mapper' ),
                'success' => __( 'Success', 'dma-internlink-mapper' ),
                'completedWithWarnings' => __( 'Completed with warnings', 'dma-internlink-mapper' ),
                'failed' => __( 'Failed', 'dma-internlink-mapper' ),
                'stoppedSafely' => __( 'Stopped safely', 'dma-internlink-mapper' ),
                'noChanges' => __( 'No changes', 'dma-internlink-mapper' ),
                'updated' => __( 'updated', 'dma-internlink-mapper' ),
                'skippedLower' => __( 'skipped', 'dma-internlink-mapper' ),
                'stopSafely' => __( 'Stop safely', 'dma-internlink-mapper' ),
                'stoppingSafely' => __( 'Stopping after this batch…', 'dma-internlink-mapper' ),
                'domainActionStopped' => __( 'The operation was stopped safely after the last completed batch. You can retry later; every source will be revalidated again.', 'dma-internlink-mapper' ),
                'domainOperationAlreadyRunning' => __( 'A domain operation is already running. Stop it safely or wait for it to finish.', 'dma-internlink-mapper' ),
                'domainActionRevalidating' => __( 'Revalidating each stored source before making changes…', 'dma-internlink-mapper' ),
                /* translators: %s: Current server-side batch number. */
                'domainActionBatch' => __( 'Processing batch %s…', 'dma-internlink-mapper' ),
                'domainActionTimedOut' => __( 'The current batch timed out. No unverified content was changed; retry the operation to continue safely.', 'dma-internlink-mapper' ),
                /* translators: 1: checked occurrences, 2: changed occurrences, 3: already-correct occurrences, 4: occurrences requiring manual editing. */
                'domainActionProgress' => __( '%1$s checked · %2$s changed · %3$s already correct · %4$s need manual editing', 'dma-internlink-mapper' ),
                /* translators: 1: checked occurrences, 2: changed occurrences, 3: already-correct occurrences, 4: occurrences requiring manual editing. */
                'domainActionFinished' => __( '%1$s checked · %2$s changed · %3$s already correct · %4$s need manual editing', 'dma-internlink-mapper' ),
                'domainActionCompleted' => __( 'Domain action completed.', 'dma-internlink-mapper' ),
                /* translators: 1: checked occurrences, 2: changed occurrences, 3: already-correct occurrences, 4: occurrences requiring manual editing, 5: first warning. */
                'domainActionFinishedWarnings' => __( 'Completed with warnings: %1$s checked · %2$s changed · %3$s already correct · %4$s need manual editing. %5$s', 'dma-internlink-mapper' ),
                /* translators: 1: checked occurrences, 2: already-correct occurrences, 3: occurrences requiring manual editing. */
                'domainActionNoChanges' => __( 'Completed: %1$s checked · %2$s already correct · %3$s need manual editing.', 'dma-internlink-mapper' ),
                /* translators: 1: checked occurrences, 2: changed occurrences, 3: already-correct occurrences, 4: occurrences requiring manual editing. */
                'domainActionPartial' => __( 'Partially completed: %1$s checked · %2$s changed · %3$s already correct · %4$s need manual editing.', 'dma-internlink-mapper' ),
                'domainActionFailed' => __( 'The domain action could not be completed safely.', 'dma-internlink-mapper' ),
                'externalActionFailed' => __( 'The link action failed.', 'dma-internlink-mapper' ),
				'externalBulkFailureDetails' => __( 'Some links were not changed:', 'dma-internlink-mapper' ),
                'plainText' => __( 'plain text', 'dma-internlink-mapper' ),
                /* translators: %s: Replacement text that will remain after removing the external link. */
                'removeExternalConfirm' => __( 'Remove this reviewed external link and preserve the surrounding content as %s? A post revision is created when WordPress revisions are enabled.', 'dma-internlink-mapper' ),
                'linkUpdated' => __( 'Link updated.', 'dma-internlink-mapper' ),
                'linkChangeFailed' => __( 'The link could not be changed safely.', 'dma-internlink-mapper' ),
                'ignoreSelectedDomains' => __( 'Ignore the domains represented by the selected links? This changes reports only.', 'dma-internlink-mapper' ),
                'ignoreSelectedOccurrences' => __( 'Ignore the selected link occurrences? This changes reports only.', 'dma-internlink-mapper' ),
                'ignored' => __( 'ignored', 'dma-internlink-mapper' ),
                'ignoreFailedCount' => __( 'failed', 'dma-internlink-mapper' ),
                'restoreIgnoredConfirm' => __( 'Restore this report item?', 'dma-internlink-mapper' ),
                'ignoreReportConfirm' => __( 'Ignore this report item? Page content and rel attributes will not be changed.', 'dma-internlink-mapper' ),
                'ignoreActionFailed' => __( 'The report preference could not be changed.', 'dma-internlink-mapper' ),
                'ignoreOccurrence' => __( 'Ignore this occurrence', 'dma-internlink-mapper' ),
                'ignoreOccurrenceHelp' => __( 'Hide only this scanned occurrence from the report.', 'dma-internlink-mapper' ),
                'ignoreDomain' => __( 'Ignore this domain', 'dma-internlink-mapper' ),
                'ignoreDomainHelp' => __( 'Hide this hostname across External Link Health reports.', 'dma-internlink-mapper' ),
                'selectPageObsidian' => __( 'Select a scanned page before exporting this Obsidian neighborhood.', 'dma-internlink-mapper' ),
                'switchLight' => __( 'Switch DMA InternLink Mapper to light mode', 'dma-internlink-mapper' ),
                'switchDark' => __( 'Switch DMA InternLink Mapper to dark mode', 'dma-internlink-mapper' ),
                'light' => __( 'Light', 'dma-internlink-mapper' ),
                'dark' => __( 'Dark', 'dma-internlink-mapper' ),
                'mapZoomControls' => __( 'Map zoom controls', 'dma-internlink-mapper' ),
                'zoomIn' => __( 'Zoom in', 'dma-internlink-mapper' ),
                'zoomOut' => __( 'Zoom out', 'dma-internlink-mapper' ),
                'fitMap' => __( 'Fit map', 'dma-internlink-mapper' ),
                'resetZoom' => __( 'Reset zoom', 'dma-internlink-mapper' ),
                'switchToLight' => __( 'Switch to light mode', 'dma-internlink-mapper' ),
                'switchToNight' => __( 'Switch to night mode', 'dma-internlink-mapper' ),
                'night' => __( 'Night', 'dma-internlink-mapper' ),
                'knowledgeLoadFailed' => __( 'Knowledge graph could not be loaded.', 'dma-internlink-mapper' ),
                'knowledgeRequestFailed' => __( 'Knowledge graph request failed.', 'dma-internlink-mapper' ),
                'indexedPages' => __( 'Indexed pages', 'dma-internlink-mapper' ),
                'selectNodeHelp' => __( 'Select a node to see its relationships and SEO signals.', 'dma-internlink-mapper' ),
                'connected' => __( 'Connected', 'dma-internlink-mapper' ),
                'authority' => __( 'Authority', 'dma-internlink-mapper' ),
                'pageInsights' => __( 'Page Insights', 'dma-internlink-mapper' ),
                'opportunities' => __( 'Opportunities', 'dma-internlink-mapper' ),
                /* translators: %s: Export format name. */
                'exportPageRelationships' => __( 'Export %s with every scanned incoming and outgoing relationship for this completed scan.', 'dma-internlink-mapper' ),
                /* translators: %s: Selected page title. */
                'selectedPage' => __( 'Selected %s', 'dma-internlink-mapper' ),
                'selectNodeExport' => __( 'Select a page node before exporting a page report.', 'dma-internlink-mapper' ),
                'liveSignalsOn' => __( 'Live signals: ON', 'dma-internlink-mapper' ),
                'liveSignalsOff' => __( 'Live signals: OFF', 'dma-internlink-mapper' ),
                'liveLinkSignalsOn' => __( 'Live link signals on', 'dma-internlink-mapper' ),
                'liveLinkSignalsOff' => __( 'Live link signals off', 'dma-internlink-mapper' ),
                /* translators: %s: Link direction or link type. */
                'noLinksView' => __( 'No %s links match this view.', 'dma-internlink-mapper' ),
                'internalAuthority' => __( 'Internal authority', 'dma-internlink-mapper' ),
                'selectIncomingHelp' => __( 'Select a node in the graph to see incoming links.', 'dma-internlink-mapper' ),
                'selectOutgoingHelp' => __( 'Select a node in the graph to see outgoing links.', 'dma-internlink-mapper' ),
                'knowledgeRefreshed' => __( 'Knowledge Graph refreshed automatically with newer scan data.', 'dma-internlink-mapper' ),
                'graphFitted' => __( '3D graph fitted to view.', 'dma-internlink-mapper' ),
                'graph3dHelp' => __( '3D: drag to rotate, wheel to zoom, Shift+drag to pan.', 'dma-internlink-mapper' ),
                'graph2dActive' => __( '2D Knowledge Graph active.', 'dma-internlink-mapper' ),
                'nodeSelectedDrag' => __( 'Node selected. Drag to reposition it; Alt/Option + drag changes depth.', 'dma-internlink-mapper' ),
                'rotate3d' => __( 'Rotate 3D graph.', 'dma-internlink-mapper' ),
                'nodeRepositioned3d' => __( 'Node repositioned in the 3D view.', 'dma-internlink-mapper' ),
                'nodeSelected' => __( 'Node selected.', 'dma-internlink-mapper' ),
                'graphPanned' => __( '3D graph panned.', 'dma-internlink-mapper' ),
                'graphRotated' => __( '3D graph rotated.', 'dma-internlink-mapper' ),
                'noPageSelected' => __( 'No page selected', 'dma-internlink-mapper' ),
                'excellent' => __( 'Excellent', 'dma-internlink-mapper' ),
                'good' => __( 'Good', 'dma-internlink-mapper' ),
                'needsWork' => __( 'Needs work', 'dma-internlink-mapper' ),
                'recommendations' => __( 'Recommendations', 'dma-internlink-mapper' ),
                'noDiagnosis' => __( 'No crawl diagnosis available', 'dma-internlink-mapper' ),
                'redirects' => __( 'Redirects', 'dma-internlink-mapper' ),
                'healthy' => __( 'Healthy', 'dma-internlink-mapper' ),
                'untitled' => __( 'Untitled', 'dma-internlink-mapper' ),
                'noAnchorText' => __( 'No anchor text', 'dma-internlink-mapper' ),
                'externalUnresolved' => __( 'External or unresolved', 'dma-internlink-mapper' ),
                'pageNotIncluded' => __( 'Page not included in scan', 'dma-internlink-mapper' ),
                'freshScanRequired' => __( 'Fresh scan required', 'dma-internlink-mapper' ),
                'unknownPage' => __( 'Unknown page', 'dma-internlink-mapper' ),
                'noAnchor' => __( 'No anchor', 'dma-internlink-mapper' ),
                'noAnchorRecorded' => __( 'No anchor text recorded', 'dma-internlink-mapper' ),
                /* translators: %s: Number of additional connections that will be displayed. */
                'loadMoreConnections' => __( 'Load %s more', 'dma-internlink-mapper' ),
                /* translators: %s: Number of connections that are not currently displayed. */
                'connectionsRemaining' => __( '%s connections remaining', 'dma-internlink-mapper' ),
                /* translators: %s: Page number. */
                'pageNumber' => __( 'Page #%s', 'dma-internlink-mapper' ),
                /* translators: %s: Link direction. */
                'noDirectionLinks' => __( 'No %s links match this view.', 'dma-internlink-mapper' ),
                'failedShort' => __( 'Failed', 'dma-internlink-mapper' ),
                /* translators: 1: Number of opportunities, 2: Number of candidates. */
                'completeOpportunities' => __( 'Complete · %1$s opportunities from %2$s candidates', 'dma-internlink-mapper' ),
                /* translators: 1: Destination title, 2: Destination URL or type, 3: Keyword. */
                'destinationSummary' => __( 'Destination: %1$s · %2$s · Keyword: %3$s', 'dma-internlink-mapper' ),
                'previewOpportunityTitle' => __( 'Preview internal-link opportunity', 'dma-internlink-mapper' ),
                'confirmInsertionTitle' => __( 'Confirm internal-link insertion', 'dma-internlink-mapper' ),
                'inserted' => __( 'Inserted', 'dma-internlink-mapper' ),
                'internalLinkNotInsertable' => __( 'Internal link not insertable', 'dma-internlink-mapper' ),
                'outdated' => __( 'Outdated', 'dma-internlink-mapper' ),
                'skipped' => __( 'Skipped', 'dma-internlink-mapper' ),
                'close' => __( 'Close', 'dma-internlink-mapper' ),
                'previewPassed' => __( 'Preview passed', 'dma-internlink-mapper' ),
                'notInserted' => __( 'Not inserted', 'dma-internlink-mapper' ),
                'insertionFailed' => __( 'Insertion failed', 'dma-internlink-mapper' ),
                'noDetails' => __( 'No details returned.', 'dma-internlink-mapper' ),
                'selectEligible' => __( 'Select at least one eligible opportunity.', 'dma-internlink-mapper' ),
                'previewLiveConfirm' => __( 'Preview Mode is active, so no links will be added. Switch to Live Mode and write the selected links into content now? A WordPress revision will be created when enabled in Settings.', 'dma-internlink-mapper' ),
                'enablingLiveMode' => __( 'Enabling Live Mode…', 'dma-internlink-mapper' ),
                'liveModeEnableFailed' => __( 'Live Mode could not be enabled.', 'dma-internlink-mapper' ),
                'liveModeStarting' => __( 'Live Mode enabled. Starting selected links…', 'dma-internlink-mapper' ),
                'liveModeTimeout' => __( 'Enabling Live Mode timed out.', 'dma-internlink-mapper' ),
                'internalLinkInsertedTitle' => __( 'Internal link inserted successfully', 'dma-internlink-mapper' ),
                'internalLinkInsertedHelp' => __( 'The verified internal link was added to the source content and confirmed after saving.', 'dma-internlink-mapper' ),
                'internalLinkNotInsertedTitle' => __( 'Internal link not inserted', 'dma-internlink-mapper' ),
                'internalLinkNotInsertedHelp' => __( 'No link was written. Review the reason and preview the opportunity again if needed.', 'dma-internlink-mapper' ),
                'previewCompleted' => __( 'Preview completed', 'dma-internlink-mapper' ),
                'previewCompletedHelp' => __( 'The selected opportunity was verified safely. No content has been changed.', 'dma-internlink-mapper' ),
                'insertionSkipped' => __( 'Insertion skipped', 'dma-internlink-mapper' ),
                'noContentChanged' => __( 'No content was changed.', 'dma-internlink-mapper' ),
                /* translators: 1: Current item number, 2: Total number of items. */
                'processingProgress' => __( 'Processing %1$s / %2$s…', 'dma-internlink-mapper' ),
                /* translators: 1: Inserted count, 2: Skipped count, 3: Failed count. */
                'finishedCounts' => __( 'Finished: %1$s inserted · %2$s skipped · %3$s failed', 'dma-internlink-mapper' ),
                'linkNowLive' => __( 'The link is now live', 'dma-internlink-mapper' ),
                'insertionTimeout' => __( 'The insertion request timed out. WordPress may still have saved the content; open the source page before retrying.', 'dma-internlink-mapper' ),
                'insertionRequestFailed' => __( 'The insertion request failed.', 'dma-internlink-mapper' ),
                'liveModeResultNotice' => __( 'Live Mode enabled. Close this dialog, select the opportunities again, and run Insert Selected Links to write them into content.', 'dma-internlink-mapper' ),
                'liveModeRunAgain' => __( 'Live Mode enabled. Run Insert Selected Links again to write approved links.', 'dma-internlink-mapper' ),
                /* translators: 1: Current opportunity number, 2: Total selected opportunities. */
                'checkingSelected' => __( 'Checking selected opportunities %1$s / %2$s…', 'dma-internlink-mapper' ),
                'safetyPreviewProgress' => __( 'Safety preview in progress.', 'dma-internlink-mapper' ),
                'notCurrentlyInsertable' => __( 'This opportunity is not currently insertable.', 'dma-internlink-mapper' ),
                /* translators: 1: Current item number, 2: Total items, 3: Number of verified links. */
                'safetyCheckCompleteAction' => __( 'Safety check complete %1$s / %2$s. %3$s verified links…', 'dma-internlink-mapper' ),
                /* translators: 1: Current item number, 2: Total items. */
                'safetyCheckComplete' => __( 'Safety check complete %1$s / %2$s.', 'dma-internlink-mapper' ),
                'visualizationLimited' => __( 'This graph is limited for browser performance. Totals describe the full scanned dataset; graph metrics describe only the visualized subset.', 'dma-internlink-mapper' ),
            ),
        ) );
    }

}
